### ISSUE TITLE
Flipper edition is 2018

### ISSUE THREAD

**Issue by ltfschoen** [shawntabrizi/substrate-contracts-workshop#2]
When I run the command `cargo contract new flipper` at https://shawntabrizi.github.io/substrate-contracts-workshop/#/0/creating-an-ink-project, there is a Cargo.toml in the files that it generates, and it says `edition = "2018"`.

Will this be changed to 2019 upon release?

**Comment by shawntabrizi** [comment]
I think this version is related to [Rust 2018](https://blog.rust-lang.org/2018/07/27/what-is-rust-2018.html)

So, if a new Rust comes out, that value will update, but it is not related to any dates that we control
