### ISSUE TITLE
Build script shown in workshop is outdated and does not match latest build.sh generator in ink! source code 

### ISSUE THREAD

**Issue by ltfschoen** [shawntabrizi/substrate-contracts-workshop#8]
When I look at the build.sh source code that's published on this slide in the workshop: https://shawntabrizi.github.io/substrate-contracts-workshop/#/0/building-your-contract

It differs from the latest ink! source code that generates flipper and that build.sh file https://github.com/paritytech/ink/blob/master/cli/src/cmd/new.rs#L164

**Comment by shawntabrizi** [comment]
@ltfschoen you need to run `cargo install --force --git https://github.com/paritytech/ink cargo-contract` again

It should have been updated by now.
