### ISSUE TITLE
Explicitly mention that rust requires wasm32-unknown-unknown target

### ISSUE THREAD

**Issue by pepyakin** [shawntabrizi/substrate-contracts-workshop#9]
When I tried to build the contract, I stumbled upon this error:

```
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-unknown-unknown` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `void`.
```

I think you get the `wasm32-unknown-unknown` just by installing substrate via one-liner. However, I think it might be worthwhile to mention in the docs that this target is required for people who already installed substrate but don't have the required target for some reason (e.g. they updated nightly).

**Comment by ltfschoen** [comment]
I think this is because the Wasm target isn't installed for the toolchain.
I tried the following but it still resulted in an error:

```
rustup default stable
rustup target add wasm32-unknown-unknown --toolchain stable
./build.sh
```

**Comment by Robbepop** [comment]
Try `rustup default nightly-2019-04-20`

**Comment by sectore** [comment]
```
rustup default nightly
rustup target add wasm32-unknown-unknown
./build
```
^ works for me while having same issues...

**Comment by lsaether** [comment]
As long as `ink!` is pinned to a specific nightly version, should we change the setup instructions to reflect this?

```
rustup update nightly
rustup update stable

rustup target add wasm32-unknown-unknown --toolchain nightly
```

Would become

```
rustup install nightly-2019-04-20
rustup target add wasm32-unknown-unknown --toolchain nightly-2019-04-20
```

**Comment by shawntabrizi** [comment]
This is solved by https://github.com/shawntabrizi/substrate-contracts-workshop/pull/23

If anyone else runs into this same error, and these new instructions do NOT solve it for you, let me know!
